Types = {
    'Login/Logout': '01',
    'PLC': '02',
    'Camera/Imaging': '03',
    'Labeling': '04',
    'Training': '05',
    'Database': '06',
    'Others': '07',
}

SubTypes = {
    # Login/Logout
    'Login_successfully':'01-1',
    'Login_eror':'01-2',
    'Logout_successfully':'01-3',
    'Logout_unsuccessfully':'01-4',
    'Login_empty_click':'01-05',
    # PLC
    'plc_connection_apply': '02-1',
    'plc_connection_apply_failed': '02-2',
    'plc_disconnected_by_error': '02-3',
    'plc_disconnected': '02-4',
    'plc_disconnected_failed': '02-5',
    'plc': '02-6',
    # Camera/Imaging
    'cameras': '03-1',
    'cameras_capturing_eror':'03-2',
    'set_sheet_detail_error': '03-3',
    'set_sheet_detail': '03-4',
    # Labeling
    'labeling_load_image_eror':'04-1',
    # Training
    'set_training_default_params': '05-1',
    'parameters_error': '05-2',
    # Database
    'database_get_plc_params_failed': '06-1',
    'database_get_plc_params': '06-2',
    'database_get_plc_ip_failed': '06-3',
    'database_get_plc_ip': '06-4',
    'REMOVE_PIP': '06-5',
    'REMOVE_PIP_FAILED': '06-6',
    'database_get_bmodels': '06-7',
    'database_conection_failed': '06-8',
    'database_get_bmodels_failed': '06-9',
    'database_add_bmodel': '06-10',
    'database_add_bmodel_failed': '06-11',
    'database_get_lmodels': '06-12',
    'database_get_lmodels_failed': '06-13',
    'database_add_lmodel': '06-14',
    'database_add_lmodel_failed': '06-15',
    'database_get_classmodels': '06-16',
    'database_get_classmodels_failed': '06-17',
    'database_get_filtered_cls_models': '06-18',
    'database_get_filtered_cls_models_failed': '06-19',
    'database_get_defects': '06-20',
    'database_get_defects_failed': '06-21',
    'database_get_defect_groups': '06-22',
    'database_get_defect_groups_failed': '06-23',
    'database_get_datasets': '06-24',
    'database_get_datasets_failed': '06-25',
    'connected_to_mysql_server': '06-26',
    'connected_to_database': '06-27',
    'error_connecting_to_mysql': '06-28',
    'mysql_connection_closed': '06-29',
    'error_reading_from_mysql': '06-30',
    # Others
    'SET_DATASET': '071',
    'SET_DATASET_FAILED': '07-2',
    'CREATE_DATASET_EXIST': '07-3',
    'CREATE_DATASET': '07-4',
    'CREATE_DATASET_FAILED': '07-5',
    'piechart_create_failed': '07-6',
    'clslist_piechart_created': '07-7',
    'update_classlist_piechart_failed': '07-8',
    'binarylist_piechart_created': '07-9',
    'update_binarylist_piechart_failed': '07-10',
    'MAXIMIZE_IMAGE_ERROR': '07-11',
    'BUILD_BINARYLIST_SLIDER_ERROR': '07-12',
    'READ_BINARYLIST_IMAGES_ERROR': '07-13',
    'LOAD_IMAGES_WITH_DEFECT': '07-14',
    'FILTERED_RESAULTS_SUCCUSSFULL': '07-15',
    'ui_get_bmodel_filter_params_failed': '07-16',
    'BINARYLIST_SLIDER_build': '07-17',
    'UI_CREATED': '07-18',
    'language_font': '07-19',
    'new_alert': '07-20',
    'left_menu': '07-21',
    'extra_left_menu': '07-21',
    'dorsa_label': '07-22',
    'show_login_window': '07-23',
    'create_login_window': '07-24',
    'minimize_window': '07-25',
    'close_window': '07-26',
    'maximize_minimize_window': '07-27',
    'get_selected_images': '07-28',
    'dataloader_window': '07-29',
    'create_ds_selection_window': '07-30',
    'ds_params_error': '07-31',
    'Sheet_page_eror':'07-32',
    'Sheet_empty':'07-33',
    'Sheet_loaded':'07-34',
    'Sheet_loaded_eror':'07-35',
    'Open_folder_eror':'07-36',
    'show_sheets_info':'07-37',
    'show_sheets_info_eror':'07-37',
    'sheet_window_search_error':'07-38'
}